server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerInvoice
    username: root
    password: Kunal1234
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8DBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never
